version: "3"
services:
  traefik:
    image: "traefik:v2.1.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mariadb:10.3.22
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
    - 3307:3306

  smtp:
    image: djfarrelly/maildev
    command: "maildev --smtp 25 --web 8080"
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.smtp.loadbalancer.server.port=8080"
      - "traefik.http.routers.smtp.rule=Host(`smtp.blogapp.com`)"
    networks:
      default:
        aliases:
          - smtp.blogapp.com
    ports:
      - "8081:8080"

  blackd:
    restart: always
    image: docker.io/pyfound/black
    command: blackd --bind-host 0.0.0.0 --bind-port 45484
    ports:
      - "45484:45484"

  django:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    user: "${UID}:${GID}"
    command: "./manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./:/opt/app-root/src
    depends_on:
      - db
      - traefik
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DJANGO_URL}`)"
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 30
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
      DJANGO_DB_NAME: '${MYSQL_DATABASE}'
      DJANGO_DB_USER: '${MYSQL_ROOT_USER}'
      DJANGO_DB_PW: '${MYSQL_PASSWORD}'
      DJANGO_DB_HOST: '${DJANGO_DB_HOST}'
      DJANGO_DB_PORT: '${DJANGO_DB_PORT}'
      DEBUG_TOOLBAR: '${DEBUG_TOOLBAR}'
      FRONTEND_SITE_NAME: '${FRONTEND_SITE_NAME}'
      FRONTEND_DOMAIN: '${FRONTEND_DOMAIN}'
      FRONTEND_PORT: '${FRONTEND_PORT}'
      FRONTEND_PROTOCOL: '${FRONTEND_PROTOCOL}'
      EMAIL_BACKEND: '${EMAIL_BACKEND}'
      EMAIL_HOST: '${EMAIL_HOST}'
      EMAIL_PORT: '${EMAIL_PORT}'
      EMAIL_FROM: '${EMAIL_FROM}'
    networks:
      default:
        aliases:
          - api.blogapp.com
