# Generated by Django 4.1.1 on 2022-11-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
