# Generated by Django 4.1.1 on 2022-11-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userstatus_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date opened')),
                ('date_closed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date closed')),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='author_request',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
